### PR TITLE
Updated for mongoid 3.0 and moped

### PR DESCRIPTION
**Pull request by gboruk**

### CODE REVIEW

**Comment by astjohn** [comment]
Any plans to merge this?

**Comment by j-wilkins** [comment]
+1 for this.

**Comment by calebjclark** [comment]
I'm about to pull most of these commits into the master branch. I am going to leave 3259c16 out of the merge for now since it requires ActiveSupport, and I'd like Mongoid::Taggable to work without requiring Rails or ActiveSupport. I may put 12c47d4 on the bench as well. Most urgent issue is getting Mongoid::Taggable working with Mongoid 3.

**Comment by wilkerlucio** [comment]
being really fair, I'm years without even touching Mongo and this stuff, I'm really willing to give someone else (that will be more engaged) the repo ownership (also the gem ownership), just let me know. thanks

**Comment by astjohn** [comment]
I've been using Mongoid::Taggable with Mongoid 3 for a while now...  check out my branch if need be:
https://github.com/astjohn/mongoid_taggable/commits/mongoid3

**Comment by calebjclark** [comment]
@wilkerlucio if you'll add me as the repo and gem owner, I'll step up and manage this project. We've been using this gem with Mongoid 3 for awhile now. I figured I might as well get it in shape for everyone else.

**Comment by wilkerlucio** [comment]
@calebclark you have being on collaborators from this repo for a while, I think you just don't noticed that, hehehhe. I also added @astjohn 

feel free to maintain it guys, I apologize for not being doing it, I just stopped to using Mongo on this time =/

**Comment by calebjclark** [comment]
@astjohn I'm merging your branch with mine, then I'll push to wilkerlucio master.

@wilkerlucio can you add me as a gem owner so we can update the gem once everything is cleaned up?

**Comment by wilkerlucio** [comment]
@calebclark please PM me your email so I can add you as owner on the gem

**Comment by calebjclark** [comment]
@wilkerlucio just sent you an email.

**Comment by calebjclark** [comment]
Gem version 1.x has been released with support for Mongoid 3. I'm closing out this pull request.

**Pull request closed without merging**
