### PR TITLE
Use rvm and bundler

### PR DESCRIPTION
**Pull request by coffeencoke**
Use an rvmrc file so we can develop using a gemset for this project.

Use gemfile to define gem dependencies.

### CODE REVIEW

**Comment by wilkerlucio** [comment]
Hi Coffeecoke,

Thanks for the help, will be really nice to make use of bundler helpers for gems, but there are some conventions that can still be followed for this, for example:

1 - for gems, its not recommended to have Gemfile.lock in repository, because the gem should work with flexible dependencies
2 - I mean we can also remove jeweler in this case, and make use of gemspec on Gemfile, a more detailed description about it can be found on: http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/
3 - use more dynamic directives on gemspec in order to get rid of Jeweler

if you apply those changes I will be happy to apply the patch. Thanks :)

**Comment by coffeencoke** [comment]
I will have to look into your points for #'s 2 and 3 but I disagree with #1.

The page you gave me, though from yehuda, is from December 2010 and a lot has changed in terms of how to use the Gemfile.lock since then.  If you look at the bundler website (http://gembundler.com) it states the following:

"Make sure to add Gemfile.lock to your repository. This will ensure that other developers on your app, as well as your deployment environment, use exactly the same third-party code as you just installed."

From my experience, it is wise to commit the lock file in order to guarantee that the next person who runs bundle install will not get a different commit from what I used (guaranteeing stability), unless they apply bundle update.

**Comment by wilkerlucio** [comment]
Hi Coffeecoke, about the #1, read this part at end of the article:

> Update
> Just to clarify, you should check in your Gemfile.lock in applications, **and not in gems**. The Gemfile.lock remembers the exact versions and sources of every piece of third-party code that you use. For applications, you want this. When developing a gem, this can obscure issues that will occur because gems are deployed (using the gem command) without the benefit of bundler.

I made the part of gem in bold. In fact, the Gemfile.lock is nice for applications, but not for gems ;)

**Comment by coffeencoke** [comment]
touchè :)

thank you

**Pull request closed without merging**
